### ISSUE TITLE
Segfault in complex finite difference stencil in multithreaded 

### ISSUE THREAD

**Issue by Chiil** [JuliaSIMD/LoopVectorization.jl#305] opened 2021-07-25 13:14 UTC
I made a stencil generator for a 3D finite difference model that generates a complex stencil on a staggered grid. The usage of `@tturbo` results in a segfault in multithreaded mode, although the single thread performance is excellent. The code can be found on GitHub [here](https://github.com/microhh/stencilbuilder/blob/master/julia/stencil_julia_4th.jl)

Since this is my first Julia experience, I would like to learn whether this is a bug, or whether I ask too much from `LoopVectorization`.

**Comment by chriselrod** [comment] 2021-07-25 16:20
It is a bug.

**Comment by Chiil** [comment] 2021-07-25 16:28
Can I do something to contribute finding the cause? I have tested to split the stencil into smaller parts in this form:
```
    @tturbo for k in ks:ke
        for j in js:je
            for i in is:ie
                @fd (ut, u, v, w) ut += (
                    - gradx(interpx(u) * interpx(u)) + visc * (gradx(gradx(u))))
                @fd (ut, u, v, w) ut += (
                    - grady(interpx(v) * interpy(u)) + visc * (grady(grady(u))))
                @fd (ut, u, v, w) ut += (
                    - gradz(interpx(w) * interpz(u)) + visc * (gradz(gradz(u))) )
            end 
        end 
    end 
```
 but then I get 
```
ERROR: LoadError: LoadError: AssertionError: length(ops) ≤ 256
Stacktrace:
 [1] adjust_offsets!(ls::LoopVectorization.LoopSet, i::Int64, array_refs_with_same_name::Vector{Int64}, arrayref_to_name_op_collection::Vector{Vector{Tuple{Int64, Int64, Int64}}})
 ```

**Comment by chriselrod** [comment] 2021-07-25 17:23
I'll raise that limit to 512.
If you want to do that locally, replace the three instances of 256 [here](https://github.com/JuliaSIMD/LoopVectorization.jl/blob/95ba84dcdbe517679eccac27a978c342b0fd3bb0/src/codegen/loopstartstopmanager.jl#L447-L448) with some larger number.

I'm guessing that there is some limit in the multithreading code being exceeded that I don't have a check on.

**Comment by chriselrod** [comment] 2021-07-25 17:41
If you're curious, one way to look into what is going on is to use `LoopVectorization.@turbo_debug`:
```julia
function kernel!(
  ut, u, v, w,
  visc, dxi, dyi, dzi, dt,
  is, ie, js, je, ks, ke)

  LoopVectorization.@turbo_debug for k in ks:ke
    for j in js:je
      for i in is:ie
        @fd (ut, u, v, w) ut += (
          - gradx(interpx(u) * interpx(u)) + visc * (gradx(gradx(u)))
          - grady(interpx(v) * interpy(u)) + visc * (grady(grady(u))) )
        @fd (ut, u, v, w) ut += (
          - gradz(interpx(w) * interpz(u)) + visc * (gradz(gradz(u))) )
      end
    end
  end
end
```
Then:
```julia
 ls = kernel!(
               ut, u, v, w,
               visc, dxi, dyi, dzi, dt,
               is, ie, js, je, ks, ke);

julia> length(ls.operations)
256
```
And we can see it has exactly 256 operations.
The first few look like:
```julia
julia> ls.operations
256-element Vector{LoopVectorization.Operation}:
 var"##op#266" = 0
 var"##op#267" = var"##DROPPED#CONSTANT##"
 var"##op#268" = var"##DROPPED#CONSTANT##"
 var"##op#269" = 0
 var"##op#270" = u[i, j + 3, k + 3]
 var"##op#271" = var"##DROPPED#CONSTANT##"
 var"##op#272" = 0
 var"##op#273" = u[i + 1, j + 3, k + 3]
 var"##op#274" = var"##DROPPED#CONSTANT##"
 var"##op#275" = 0
 var"##op#276" = u[i + 2, j + 3, k + 3]
 var"##op#277" = var"##DROPPED#CONSTANT##"
 var"##op#278" = 0
 var"##op#279" = u[i + 3, j + 3, k + 3]
 var"##op#280" = LoopVectorization.mul_fast(var"##op#278", var"##op#279")
 var"##op#281" = LoopVectorization.vfmadd_fast(var"##op#275", var"##op#276", var"##op#280")
 var"##op#282" = LoopVectorization.vfmadd_fast(var"##op#272", var"##op#273", var"##op#281")
 var"##op#283" = LoopVectorization.vfmadd_fast(var"##op#269", var"##op#270", var"##op#282")
 var"##op#284" = 0
 var"##op#285" = LoopVectorization.mul_fast(var"##op#283", var"##op#284")
 var"##op#286" = u[i + 4, j + 3, k + 3]
 var"##op#287" = LoopVectorization.mul_fast(var"##op#278", var"##op#286")
 var"##op#288" = LoopVectorization.vfmadd_fast(var"##op#275", var"##op#279", var"##op#287")
 var"##op#289" = LoopVectorization.vfmadd_fast(var"##op#272", var"##op#276", var"##op#288")
 var"##op#290" = LoopVectorization.vfmadd_fast(var"##op#269", var"##op#273", var"##op#289")
 var"##op#291" = LoopVectorization.mul_fast(var"##op#290", var"##op#284")
 var"##op#292" = u[i + 5, j + 3, k + 3]
 var"##op#293" = LoopVectorization.mul_fast(var"##op#278", var"##op#292")
 var"##op#294" = LoopVectorization.vfmadd_fast(var"##op#275", var"##op#286", var"##op#293")
 var"##op#295" = LoopVectorization.vfmadd_fast(var"##op#272", var"##op#279", var"##op#294")
```

Something I notice here is that I should improve the CSE of many of the operations.


Anyway, I found the cause of the problem.

**Comment by Chiil** [comment] 2021-07-25 17:49
Thanks for looking into this. Did you find the cause of the segfault? I'd be very happy to learn where it went wrong. Also, if I run it with 4 threads instead of 2 it deadlocks here.

**Comment by chriselrod** [comment] 2021-07-25 18:03
> Thanks for looking into this. Did you find the cause of the segfault? I'd be very happy to learn where it went wrong. Also, if I run it with 4 threads instead of 2 it deadlocks here.

Yes, I found the cause of the segfault and deadlocks.

[ThreadingUtilities.jl](https://github.com/JuliaSIMD/ThreadingUtilities.jl/blob/2f7177e37152c6c3d185b18a4e2b47941e617415/src/ThreadingUtilities.jl#L25), which LoopVectorization uses for threading, defines a memory buffer of 512 bytes per thread. This is used for communicating thread-specific info.

Adding a print statement to the multithreaded code showed that this code was using over 1500 bytes. You can add `@show sizeof(args)` [to this function](https://github.com/JuliaSIMD/LoopVectorization.jl/blob/95ba84dcdbe517679eccac27a978c342b0fd3bb0/src/codegen/lower_threads.jl#L23).

The 512 byte buffers for each thread are ordered one after the other.
So if it allocates for 4 threads total, that'd be 2048 bytes total.
As a note, if you start Julia with 4 threads, it'll only allocate for 3 threads. When you run on `N` threads, it'll use `N-1` of these.

Because we were writing >1500 bytes into only 512 bytes of space, writing into thread 1's space will also write into thread 2 and thread 3's buffer, corrupting their results. This can cause a deadlock, because this space is also used to tell each thread what to do.
We can also get a segfault in two ways:
1) Because we're corrupting data, we can easily get a segfault when one array's pointer is replaced with junk.
2) The normal way you get segfaults by writing past the end of allocated memory.

A hack-ish fix would be to change that constant in ThreadingUtilties. Maybe I'll do that.
But I'll also decrease the amount of memory LoopVectorization is using here.
Most of that memory is used for all the constants like `9/16` that're used inside the loop. I'll have it transmit those constants another way (that doesn't use this memory).

**Comment by Chiil** [comment] 2021-07-25 20:48
Following your comments on the memory usage for the constants, I replaced them by symbols, and now the code runs without segfault or deadlock. The code is [here](https://github.com/microhh/stencilbuilder/blob/master/julia/stencil_julia_4th_constants.jl)

**Comment by chriselrod** [comment] 2021-07-25 21:22
I haven't tried that yet, but on #306 it is probably better to leave them as literals.

**Comment by Chiil** [comment] 2021-07-25 21:28
OK cool. So I am rather new to Julia so how will I now be able to fetch the updated package?

**Comment by chriselrod** [comment] 2021-07-25 21:37
Because of an oversight on my part (needing the new VectorizationBase release, because of unrelated changes), you'll have to wait until [this PR merges](https://github.com/JuliaRegistries/General/pull/41495) before `using LoopVectorization` can work on the PR.
So I'd wait until that merges, and then update packages to get VectorizationBase v0.20.25.

Then, to try out that PR, you can `] dev LoopVectorization`.
This will clone the repository into `~/.julia/dev/LoopVectorization`.

From there, you'll need to checkout the branch. Are you familiar/comfortable with git? If so, you'd probably already have a preferred way to do that.
If not, you could consider taking a look at things like git graken (a GUI) or (if you're using emacs as your editor) magit to do this. Throwing those out there as two popular methods that don't use the command line.
Two means using the command line:
1. Install [GitHub's command line tool](https://github.com/cli/cli). Then, you should be able to navigate to the LoopVectorization folder, and simply run `gh pr checkout 306`.
2. If you'd rather avoid installing anything extra (other than `git`, if not already installed), you could navigate to LoopVectorization's folder and do `git fetch origin`, and then `git checkout origin/interpretconstsmoreaccurateregpress`.

Later, after that PR's been merged and a new release of LoopVectorization has been made, you can `] add LoopVectorization` from Julia to get back to the release version.

**Comment by Chiil** [comment] 2021-07-26 08:13
This works very well, thanks a lot, my code is running again. Also, after your work the `btime` output displays 0 allocations, where this used to be a larger number.

**Comment by Chiil** [comment] 2021-07-26 10:10
Splitting the stencil again leads as in the code [here](https://github.com/microhh/stencilbuilder/blob/master/julia/stencil_julia_4th.jl) a new error. If I remove the literals and put them into constants, the code runs.

```
ERROR: LoadError: LoadError: InexactError: trunc(UInt8, 256)
Stacktrace:
  [1] throw_inexacterror(f::Symbol, #unused#::Type{UInt8}, val::Int64)
    @ Core ./boot.jl:602
  [2] checked_trunc_uint
    @ ./boot.jl:632 [inlined]
  [3] toUInt8
    @ ./boot.jl:694 [inlined]
  [4] UInt8
    @ ./boot.jl:754 [inlined]
  [5] convert
    @ ./number.jl:7 [inlined]
  [6] OperationStruct
    @ ~/.julia/dev/LoopVectorization/src/condense_loopset.jl:138 [inlined]
  [7] OperationStruct!(varnames::Vector{Symbol}, ids::Vector{Int64}, ls::LoopVectorization.LoopSet, op::LoopVectorization.Operation)
    @ LoopVectorization ~/.julia/dev/LoopVectorization/src/condense_loopset.jl:209
  [8] generate_call_types(ls::LoopVectorization.LoopSet, preserve::Vector{Symbol}, shouldindbyind::Vector{Bool}, roots::Vector{Bool}, extra_args::Expr, ::Tuple{Bool, Int8, Int8}, thread::UInt64, debug::Bool)
    @ LoopVectorization ~/.julia/dev/LoopVectorization/src/condense_loopset.jl:652
  [9] generate_call_split(ls::LoopVectorization.LoopSet, preserve::Vector{Symbol}, shouldindbyind::Vector{Bool}, roots::Vector{Bool}, extra_args::Expr, inlineu₁u₂::Tuple{Bool, Int8, Int8}, thread::UInt64, debug::Bool)
    @ LoopVectorization ~/.julia/dev/LoopVectorization/src/condense_loopset.jl:634
 [10] generate_call(ls::LoopVectorization.LoopSet, inlineu₁u₂::Tuple{Bool, Int8, Int8}, thread::UInt64, debug::Bool)
    @ LoopVectorization ~/.julia/dev/LoopVectorization/src/condense_loopset.jl:623
 [11] setup_call(ls::LoopVectorization.LoopSet, q::Expr, source::LineNumberNode, inline::Bool, check_empty::Bool, u₁::Int8, u₂::Int8, thread::Int64, warncheckarg::Int64)
    @ LoopVectorization ~/.julia/dev/LoopVectorization/src/condense_loopset.jl:802
 [12] turbo_macro(mod::Module, src::LineNumberNode, q::Expr, args::Expr)
    @ LoopVectorization ~/.julia/dev/LoopVectorization/src/constructors.jl:121
 [13] var"@tturbo"(__source__::LineNumberNode, __module__::Module, args::Vararg{Any, N} where N)
    @ LoopVectorization ~/.julia/dev/LoopVectorization/src/constructors.jl:232
    ```

**Comment by Chiil** [comment] 2021-07-26 12:45
I think my new message and the closing of the issue crossed. Please have a look to the message above, the issue is still persistent, but with a slightly different error. It seems that the size of my stencil is still at the edge of what is possible.

**Closed** 2021-07-27 00:12 UTC
