### ISSUE TITLE
Trivial loop throws KeyError

### ISSUE THREAD

**Issue by cafaxo** [JuliaSIMD/LoopVectorization.jl#452] opened 2022-12-28 12:53 UTC
The following trivial loop causes a compilation error:

```julia
julia> using LoopVectorization

julia> function foo!(z, x)
    @turbo for i = 1:1
        z[1] += x[1]
    end
end
ERROR: LoadError: KeyError: key Symbol("###RHS###3###") not found
```

This comes up as a special case from some automatically generated code. Strictly speaking it satisfies the requirements for `@turbo` and should probably not error out.

**Comment by chriselrod** [comment] 2022-12-28 20:44
Duplicate of https://github.com/JuliaSIMD/LoopVectorization.jl/issues/331

**Closed by chriselrod** 2022-12-28 20:44 UTC

**Comment by chriselrod** [comment] 2022-12-28 20:45
Well, accept that it's `z[1] += x[1]` instead of `z[1] += x[i]`, so maybe not an exact duplicate.

**Comment by chriselrod** [comment] 2022-12-28 20:50
PRs welcome. THe same approach mentioned in the linked thread works, even though we also have `x[1]` instead of `x[i]`.
```julia
julia> using LoopVectorization

julia> function foo_noturbo!(z, x)
            @inbounds for i = 1:1
               z[1] += x[1]
           end
       end
foo_noturbo! (generic function with 1 method)

julia> function foo_noturbo!(z, x)
            @inbounds for i = 1:1
               z[1] += x[1]
           end
           z
       end
foo_noturbo! (generic function with 1 method)

julia> function foo!(z, x)
           s = zero(eltype(z))
           @turbo for i = 1:1
               s += x[1]
           end
           @inbounds z[1] += s
       end
foo! (generic function with 1 method)

julia> x = rand(1)
1-element Vector{Float64}:
 0.9754894452989981

julia> z = zero(x);

julia> foo_noturbo!(z,x)
1-element Vector{Float64}:
 0.9754894452989981

julia> foo!(z,x)
1.9509788905979961

julia> z[1]=0;

julia> foo!(z,x)
0.9754894452989981
```
