### ISSUE TITLE
Wrong results on 1.7 with LoopVectorization v0.11

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaSIMD/LoopVectorization.jl#294] opened 2021-06-23 15:48 UTC
Tested with Julia 1.7. MWE produces wrong result for matrix multiplication.
```
using LinearAlgebra
using LoopVectorization
function mulCAtB!(C, A, B)
    M, N = size(C); K = size(B,1)
    @assert size(C, 1) == size(A, 2)
    @assert size(C, 2) == size(B, 2)
    @assert size(A, 1) == size(B, 1)
    # When the @avx macro is available, this code is faster:
    # z = zero(eltype(C))
    @avx for n in 1:size(C,2), m in 1:size(C,1)
        Cmn = zero(eltype(C)) # Cmn = z # For some reason this bombed in LoopVectorization 0.4.0
        for k in 1:size(A,1)
            Cmn += A[k,m] * B[k,n]
        end
        C[m,n] = Cmn
    end
    return C
end
ecoords = [50.0 200.0 91.66666666666667; 50.0 200.0 100.0; 33.333333333333336 200.0 100.0; 33.333333333333336 188.88888888888889 91.66666666666667; 50.0 200.0 95.83333333333334; 41.66666666666667 200.0 100.0; 41.66666666666667 200.0 95.83333333333334; 41.66666666666667 194.44444444444446 91.66666666666667; 41.66666666666667 194.44444444444446 95.83333333333334; 33.333333333333336 194.44444444444446 95.83333333333334]
gradNparams = [0.4472136 0.4472136 0.4472136; -0.4472136 0.0 0.0; 0.0 -0.4472136 0.0; 0.0 0.0 1.3416408; 0.0 -0.5527864 -0.5527864; 0.5527864 0.5527864 0.0; 
-0.5527864 0.0 -0.5527864; -2.3416408 -2.3416408 -1.7888544; 2.3416408 0.0 0.5527864; 0.0 2.3416408 0.5527864]
J = fill(0.0, 3, 3)
mulCAtB!(J, ecoords, gradNparams) 
@show J
# = [0.0 -94.72136 -35.09288000000001; 0.0 -455.31904444444444 -118.59735555555561; 8.333333333333343 -216.07391 -52.97536333333335]                                                    
J = ecoords' * gradNparams 
# = [-3.060506514884766e-16 -16.666666666666668 -16.666666666666664; -3.308661765307382e-14 2.3756801207734194e-14 -11.111111111111141; 8.333333333333341 8.333333333333341 -1.4983082034329223e-15]                                          
```

**Comment by chriselrod** [comment] 2021-06-23 16:16
Can you reproduce on 1.6?

**Comment by PetrKryslUCSD** [comment] 2021-06-23 16:23
No sir, it works correctly on 1.6. 

On 1.8 I get:
```
julia> include("junk.jl")                                                
J = [0.0 -94.72136 -35.09288000000001; 0.0 -455.31904444444444 -118.59735555555561; 8.333333333333343 -216.07391 -52.97536333333335]              
3×3 Matrix{Float64}:                                                     
 -3.06051e-16  -16.6667       -16.6667                                   
 -3.30866e-14    2.37568e-14  -11.1111                                   
  8.33333        8.33333       -1.49831e-15                              
                                                                         
julia> versioninfo()                                                     
Julia Version 1.8.0-DEV.56                                               
Commit ae1b469264 (2021-06-19 16:21 UTC)                                 
Platform Info:                                                           
  OS: Windows (x86_64-w64-mingw32)                                       
  CPU: Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz                          
  WORD_SIZE: 64                                                          
  LIBM: libopenlibm                                                      
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)                                 
Environment:                                                             
  JULIA_SSL_CA_ROOTS_PATH =      
```
so incorrect result.

**Comment by chriselrod** [comment] 2021-06-23 16:38
```julia
julia> J = fill(0.0, 3, 3)
3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> mulCAtB!(J, ecoords, gradNparams)
3×3 Matrix{Float64}:
 0.0      -16.6667       -16.6667
 0.0       -1.42109e-14  -11.1111
 8.33333    8.33333       -7.10543e-15

julia> @show J
J = [0.0 -16.66666666666667 -16.666666666666664; 0.0 -1.4210854715202004e-14 -11.111111111111143; 8.333333333333371 8.333333333333371 -7.105427357601002e-15]
3×3 Matrix{Float64}:
 0.0      -16.6667       -16.6667
 0.0       -1.42109e-14  -11.1111
 8.33333    8.33333       -7.10543e-15

julia> # = [0.0 -94.72136 -35.09288000000001; 0.0 -455.31904444444444 -118.59735555555561; 8.333333333333343 -216.07391 -52.97536333333335]          
       J = ecoords' * gradNparams
3×3 Matrix{Float64}:
 -3.06051e-16  -16.6667       -16.6667
 -3.30866e-14    2.37568e-14  -11.1111
  8.33333        8.33333       -1.49831e-15

julia> versioninfo()
Julia Version 1.7.0-beta2
Commit b570546b68* (2021-06-20 06:31 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake-avx512)
Environment:
  JULIA_NUM_THREADS = auto
```
I will try on a couple other computers...

**Comment by chriselrod** [comment] 2021-06-23 16:40
Also, could you run
```julia
using LoopVectorization
include(joinpath(pkgdir(LoopVectorization), "test", "testsetup.jl"))
include(joinpath(pkgdir(LoopVectorization), "test", "gemm.jl"))
```
and let me know if tests pass/fail?
Tests pass on CI. Your case here should be covered in the tests.

**Comment by PetrKryslUCSD** [comment] 2021-06-23 16:46
There are test failures in all. 1.6 got the farthest before failing.

**Comment by PetrKryslUCSD** [comment] 2021-06-23 16:47
Which version of this package should i be running?

**Comment by PetrKryslUCSD** [comment] 2021-06-23 16:48
I have LoopVectorization v0.11.2

**Comment by chriselrod** [comment] 2021-06-23 16:48
0.12.43 is the latest release.

**Comment by chriselrod** [comment] 2021-06-23 16:51
But it is concerning that tests now fail in 0.11.2. Seems some of its dependencies did have breaking changes.

**Comment by chriselrod** [comment] 2021-06-23 17:13
Oh, I think I know what the problem may be.

**Comment by PetrKryslUCSD** [comment] 2021-06-23 17:17
With 0.12.43 the test passes on 1.6, 1.7, and 1.8.

**Comment by chriselrod** [comment] 2021-06-23 17:20
0.12.43 is using a newer version of VectorizationBase that includes a fix for a change in LLVM12

0.11 is using an older version of VectorizationBase that doesn't, so I'm backporting that fix here: https://github.com/JuliaSIMD/VectorizationBase.jl/commit/7ff650c90602f39b65cf7ecbadfeb2956b21840c

**Comment by PetrKryslUCSD** [comment] 2021-06-23 17:24
Thanks for looking into it. The newest LoopVectorization works for me, so I
will update my stuff to it.

**Comment by chriselrod** [comment] 2021-06-23 17:54
Closing because I just confirmed locally on my Haswell laptop that this example failed with `LoopVectorization@0.11 VectorizationBase@0.18.14` but passed with `LoopVectorization@0.11 VectorizationBase@0.18.15`.

(Although `LoopVectorization@0.12` is definitely preferred.)

**Closed by chriselrod** 2021-06-23 17:54 UTC
