### ISSUE TITLE
Incorrect results with unsigned integers of different sizes when broadcasting

### ISSUE THREAD

**Issue by ForceBru** [JuliaSIMD/LoopVectorization.jl#314] opened 2021-08-03 20:25 UTC
Code:

```julia
import Pkg
Pkg.activate(temp=true)
Pkg.add("LoopVectorization", io=devnull)
Pkg.status()

using LoopVectorization

function f(K::U, N) where U <: Unsigned
  mask::BitVector = zeros(Bool, N)
  labels::Vector{U} = [(i % K) + 1 for i ∈ 1:N]

  mask .= labels .== 1
  mask
end

function f_turbo(K::U, N) where U <: Unsigned
  mask::BitVector = zeros(Bool, N)
  labels::Vector{U} = [(i % K) + 1 for i ∈ 1:N]

  @turbo mask .= labels .== 1
  mask
end

@show sum(f(UInt8(3), 100))
@show sum(f_turbo(UInt8(3), 100))

@show sum(f(UInt16(3), 100))
@show sum(f_turbo(UInt16(3), 100))

@show sum(f(UInt32(3), 100))
@show sum(f_turbo(UInt32(3), 100))

@show sum(f(UInt64(3), 100))
@show sum(f_turbo(UInt64(3), 100))
```

Output:

```
~/test $ julia loopVec_test.jl
  Activating new environment at `/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/jl_Joui35/Project.toml`
      Status `/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/jl_Joui35/Project.toml`
  [bdcacae8] LoopVectorization v0.12.61
sum(f(UInt8(3), 100)) = 33
sum(f_turbo(UInt8(3), 100)) = 33
sum(f(UInt16(3), 100)) = 33
sum(f_turbo(UInt16(3), 100)) = 33
sum(f(UInt32(3), 100)) = 33
sum(f_turbo(UInt32(3), 100)) = 17
sum(f(UInt64(3), 100)) = 33
sum(f_turbo(UInt64(3), 100)) = 9
```

So, `sum(f(..., 100)) == 33` for all integer sizes (`UInt8` to `UInt64`), but `sum(f_turbo(..., 100))` gives incorrect results for `UInt32` and `UInt64`

**Comment by chriselrod** [comment] 2021-08-04 05:34
Hmm, guess I'll have to try on a different computer
```julia
julia> @show sum(f(UInt8(3), 100))
sum(f(UInt8(3), 100)) = 33
33

julia> @show sum(f_turbo(UInt8(3), 100))
sum(f_turbo(UInt8(3), 100)) = 33
33

julia> @show sum(f(UInt16(3), 100))
sum(f(UInt16(3), 100)) = 33
33

julia> @show sum(f_turbo(UInt16(3), 100))
sum(f_turbo(UInt16(3), 100)) = 33
33

julia> @show sum(f(UInt32(3), 100))
sum(f(UInt32(3), 100)) = 33
33

julia> @show sum(f_turbo(UInt32(3), 100))
sum(f_turbo(UInt32(3), 100)) = 33
33

julia> @show sum(f(UInt64(3), 100))
sum(f(UInt64(3), 100)) = 33
33

julia> @show sum(f_turbo(UInt64(3), 100))
sum(f_turbo(UInt64(3), 100)) = 33
33

(loopvecdev) pkg> st LoopVectorization
      Status `~/Documents/progwork/julia/env/loopvecdev/Project.toml`
  [bdcacae8] LoopVectorization v0.12.61 `~/.julia/dev/LoopVectorization`
```

**Comment by chriselrod** [comment] 2021-08-04 07:58
I was able to reproduce and fix this on another computer. The fix is in VectorizationBase 0.20.29, which I should release in the next couple of hours (after which updating to it should fix the problem).

**Comment by ForceBru** [comment] 2021-08-04 15:39
@chriselrod, I'm getting an error with the new version and the same code:

```
~/test $ julia --threads 4 loopVec_test.jl
  Activating new environment at `/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/jl_aAbM6D/Project.toml`
      Status `/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/jl_aAbM6D/Project.toml`
  [bdcacae8] LoopVectorization v0.12.61
sum(f(UInt8(3), 100)) = 33
sum(f_turbo(UInt8(3), 100)) = 33
sum(f(UInt16(3), 100)) = 33
sum(f_turbo(UInt16(3), 100)) = 33
sum(f(UInt32(3), 100)) = 33
sum(f_turbo(UInt32(3), 100)) = 33
sum(f(UInt64(3), 100)) = 33
ERROR: LoadError: ArgumentError: There is only a need for splitting a mask of size 8, but the mask is of size 4.
Stacktrace:
  [1] vstorebit_unroll_i_quote(Nm1::Int64, Wsplit::Int64, W::Int64, A::Bool, S::Bool, NT::Bool, rs::Int64, mask::Bool)
    @ VectorizationBase ~/.julia/packages/VectorizationBase/NrYMV/src/vecunroll/memory.jl:1198
  [2] #s160#365
    @ ~/.julia/packages/VectorizationBase/NrYMV/src/vecunroll/memory.jl:1228 [inlined]
  [3] var"#s160#365"(Nm1::Any, Wsplit::Any, W::Any, S::Any, A::Any, NT::Any, RS::Any, M::Any, ::Any, ptr::Any, v::Any, i::Any, m::Any, #unused#::Type, #unused#::Type, #unused#::Type, #unused#::Any)
    @ VectorizationBase ./none:0
  [4] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any, N} where N)
    @ Core ./boot.jl:571
  [5] macro expansion
    @ ~/.julia/packages/VectorizationBase/NrYMV/src/vecunroll/memory.jl:771 [inlined]
  [6] _vstore_unroll!
    @ ~/.julia/packages/VectorizationBase/NrYMV/src/vecunroll/memory.jl:761 [inlined]
  [7] _vstore!
    @ ~/.julia/packages/VectorizationBase/NrYMV/src/vecunroll/memory.jl:839 [inlined]
  [8] macro expansion
    @ ~/.julia/packages/LoopVectorization/KwKzA/src/reconstruct_loopset.jl:711 [inlined]
  [9] _turbo_!
    @ ~/.julia/packages/LoopVectorization/KwKzA/src/reconstruct_loopset.jl:711 [inlined]
 [10] macro expansion
    @ ~/.julia/packages/LoopVectorization/KwKzA/src/broadcast.jl:393 [inlined]
 [11] vmaterialize!
    @ ~/.julia/packages/LoopVectorization/KwKzA/src/broadcast.jl:393 [inlined]
 [12] f_turbo(K::UInt64, N::Int64)
    @ Main ~/test/loopVec_test.jl:20
 [13] top-level scope
    @ show.jl:955
in expression starting at /Users/forcebru/test/loopVec_test.jl:34
~/test [1] $
```

Where `/Users/forcebru/test/loopVec_test.jl:34` is the last line of the snippet posted above: 
```
@show sum(f_turbo(UInt64(3), 100))
```

-------

## Machine info

```
~/test $ uname -a
Darwin iMac-ForceBru.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64
```

```python
>>> # Python; don't know how to do this in Julia
>>> import platform
>>> platform.platform()
'macOS-10.15.7-x86_64-i386-64bit'
```

**Comment by chriselrod** [comment] 2021-08-04 15:49
In Julia:
```julia
julia> versioninfo()
Julia Version 1.7.0-beta3
Commit e76c9dad42* (2021-07-07 08:12 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake-avx512)
```

**Comment by chriselrod** [comment] 2021-08-04 16:17
CPUs without AVX2 aren't well tested, but that should be fixed by [this commit](https://github.com/JuliaSIMD/VectorizationBase.jl/commit/cd025d46258b233f3409ecf7a25afe3f1ffa9279) in VectorizationBase 0.20.30. I'll again close this issue once that version is tagged.

**Comment by ForceBru** [comment] 2021-08-04 16:17
Yeah, right, I completely forgot about this

```julia
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, ivybridge)
```

**Comment by chriselrod** [comment] 2021-08-04 16:34
With `Int64`, your CPU probably prefers to operate on them 2 at a time. With `Int32`, it'd be 4 at a time.
It might be able to use floating point operations instead of integer, which would let it do twice as many. The AVX instruction set (which your CPU has) doubled the amount of floating point, but AVX2 (which it doesn't) is needed to get most of the same benefits for integers.

With `BitArray`s, elements are individual bits.
The smallest amount of data your CPU can load/store at a time is 1 byte (8 bits).

When you do a comparison producing 4 or bits as an answer (as is the case with `UInt32` and `UInt64`, respectively), it'd still store 8 bits as a time. This means it'd write 8 bits, only 2 or 4 of which are part of the answer, meaning there'd be 8 junk bits (zeros) that overwrite previous results.
It also often wouldn't write to the correct place, because it has to write at 8-bit (1-byte) boundaries, too.

The first computer I tested on (the 7900X) has AVX512, letting it calculate with 8 `Int64` at a time, meaning it was always producing at least 8 bits worth of answers.

To fix the bug, I have it combine multiple stores. That is, instead of storing 2 bits at a time, it collects 8 bits worth of answers, and then stores them as a set.
I added an assertion making sure it's collected 8 before storing.
This resulted in your most recent error, because on the last iteration it won't end up with 8 total before it has to store.
The fix there was to just remove the assertion.

**Comment by ForceBru** [comment] 2021-08-04 17:04
The code is just a MCVE - I'm not actually generating the `labels` like this. I wrote it this way here because I wanted them to be deterministic but didn't want to hard-code a hundred of them. Didn't know about `falses`, though, - thanks!

**Closed** 2021-08-04 17:37 UTC
