### ISSUE TITLE
Bug in reduction

### ISSUE THREAD

**Issue by IlianPihlajamaa** [JuliaSIMD/LoopVectorization.jl#411] opened 2022-06-07 09:22 UTC
I think I have found a bug. I boiled it down to the following MWE: 

```julia
using LoopVectorization

function f(A)
    N1 = size(A, 1)
    N2 = size(A, 2)
    b = zeros(N1)
    for i = 1:N1
        for j = 1:N2
            b[i] += A[i, j]
        end
    end
    return b
end

function fturbo(A)
    N1 = size(A, 1)
    N2 = size(A, 2)
    b = zeros(N1)
    for i = 1:N1
        @turbo for j = 1:N2
            b[i] += A[i, j]
        end
    end
    return b
end

A = rand(1000, 500)
f1 = f(A)
f2 = fturbo(A)
all(f1 .≈ f2)
```
returns:
```julia
ERROR: LoadError: KeyError: key Symbol("###RHS###3###") not found
Stacktrace:
 [1] getindex(h::Dict{Symbol, LoopVectorization.Operation}, key::Symbol)
   @ Base .\dict.jl:481
 [2] add_reduction!(ls::LoopVectorization.LoopSet, var::Symbol, reduceddeps::Vector{Symbol}, deps::Vector{Symbol}, vparents::Vector{LoopVectorization.Operation}, reduction_ind::Int64, elementbytes::Int64, instr::LoopVectorization.Instruction)
   @ LoopVectorization C:\Users\me\.julia\packages\LoopVectorization\h0HPD\src\parse\add_compute.jl:579
in expression starting at c:\Users\me\test.jl:20
```

In the MWE, putting the `@turbo` before the outer loop instead fixes the issue. In my actual application, however, that is not possible because I need to do some more complex computations there.

```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 11
```

By the way, I believe the code above did work with LoopVectorization roughly half a year ago, but I sadly can't find the exact version I was using then.

**Comment by andrewjradcliffe** [comment] 2022-06-10 21:57
The following does not address the root issue, but it may be useful. Would the following modification work for your application? A scalar temporary (which will be more efficient than since it avoids the access/store), and, also support arbitrary indexing.

```julia
function fturbo2(A)
    b = zeros(size(A, 1))
    for i = axes(A, 1)
        b′ = zero(eltype(A))
        @turbo for j = axes(A, 2)
            b′ += A[i, j]
        end
        b[i] = b′
    end
    return b
end
```

**Comment by chriselrod** [comment] 2022-06-10 22:03
I'd suggest this as a better fix:
```julia
function fturbo(A)
    N1 = size(A, 1)
    N2 = size(A, 2)
    b = zeros(N1)
    @turbo for i = 1:N1
        for j = 1:N2
            b[i] += A[i, j]
        end
    end
    return b
end
```

**Comment by chriselrod** [comment] 2022-06-10 22:08
This is basically a duplicate of:
https://github.com/JuliaSIMD/LoopVectorization.jl/issues/331

**Closed by chriselrod** 2022-06-10 22:08 UTC

**Comment by chriselrod** [comment] 2022-06-10 22:09
> In the MWE, putting the @turbo before the outer loop instead fixes the issue. In my actual application, however, that is not possible because I need to do some more complex computations there.

That's unfortunate. LV will in general do better the more loops it is allowed to transform and optimize.
@andrewjradcliffe's suggestion is the way to work around this issue.

It's easy to do this manually, but I'd be happy to accept a PR that automates the process.

**Comment by chriselrod** [comment] 2022-06-10 22:10
> By the way, I believe the code above did work with LoopVectorization roughly half a year ago, but I sadly can't find the exact version I was using then.

This code never worked.

**Comment by IlianPihlajamaa** [comment] 2022-06-10 22:37
> Would the following modification work for your application? 

Thanks for the suggestion! I can modify my original code to make this work.

> This is a duplicate of:
https://github.com/JuliaSIMD/LoopVectorization.jl/issues/331

Also thanks for linking the relevant issue! I understand what the problem is now. By the way, I love the package and am looking forward to seeing the rewrite when it's ready :)

> This code never worked.

Then my memory is probably failing me. I edited the original post.
